/**
 * Automatically generated file. DO NOT MODIFY
 * (Generated by generate-build-config.sh)
 */
namespace LEGODeviceUnitySDK {
    public static class BuildConfig {
        public static readonly bool DEBUG = false;
        public static readonly string APPLICATION_ID = "dk.lego.devicesdk";
        //public static readonly string BUILD_TYPE = "release";
        //public static readonly string FLAVOR = "";
        public static readonly int VERSION_CODE = -1;
        public static readonly string VERSION_NAME =  "3.1.1-SNAPSHOT";

        public static readonly string SDK_BUILD_NUMBER = "-1";
        public static readonly string SDK_GIT_HEAD_HASH = "xxxxxx";
        public static readonly string SDK_TESTED_WITH_V2_FIRMWARE_VERSION = "1.0.09.0000";
        public static readonly string SDK_TESTED_WITH_V3_FIRMWARE_VERSION = "1.0.00.0032";
        public static readonly string SDK_VERSION = "-1";
    }
}
